version: '3'

services:
  scylladb:
    image: scylladb/scylla:4.4.2
    container_name: scylla
    command: --smp 1 --memory 100M --api-address 0.0.0.0
    ports:
    - "9042:9042"
    # volume:
    # - ./data/scylla:/var/lib/scylla